name: Prod Pipeline (WEBAPP)
on:
  push:
    branches:
      - master

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: 37356d89077d2a442dc8077e043204f67f4d1eb6
          approvers: nhs3108
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "Please approve or deny the deployment of version v1.3.5."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
