on:
  repository_dispatch:
    types: [deploy-website]
    
jobs:
  run_if_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch_name }}
      - name: Log ref
        run: echo CMS will be build from ref ${GITHUB_REF##*/}
      - env:
          MESSAGE: ${{ github.event.client_payload.branch_name }}
        run: echo $MESSAGE
