on:
  repository_dispatch:
    types: [deploy-latest-release]
    
jobs:
  deploy-latest-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest release version
        id: fetch-latest-release
        uses: reloc8/action-latest-release-version@1.0.0
      - name: Log latest release tag
        run: echo ${{ steps.fetch-latest-release.outputs.latest-release }}
      - name: Checkout code to latest release tag
        run: git checkout ${{ steps.fetch-latest-release.outputs.latest-release }}
          
