on:
  repository_dispatch:
    types: [deploy-website]
    
jobs:
  run_if_failure:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.branch_name }}
        run: echo $MESSAGE
