on:
  repository_dispatch:
    types: [deploy-website]
    
jobs:
  run_if_failure:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo Start to deploy with branch ${{ github.event.client_payload.branch }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
          
